from __future__ import annotations

import datetime

import discord

from . import BaseLayoutView
from .media_gallery import MediaGallery, StepperRow

__all__: tuple[str, ...] = ("EmbedContainerView",)


class EmbedContainerView(BaseLayoutView):
    def __init__(
        self, user: discord.User | discord.Member, title: str, description: str, thumbnail: str, *, timeout: float = 60
    ) -> None:
        super().__init__(user, timeout)
        self._cursor = 0
        self._limit = 3

        section = discord.ui.Section["EmbedContainerView"](
            f"## {title}",
            description,
            accessory=discord.ui.Thumbnail["EmbedContainerView"](thumbnail),
        )
        self.media_gallery = MediaGallery(index=self._cursor)
        container = discord.ui.Container["EmbedContainerView"](
            section,
            self.media_gallery,
            StepperRow(),
            discord.ui.Separator(),
            discord.ui.TextDisplay(
                f"-# {datetime.datetime.now(tz=datetime.timezone.utc).strftime('%Y-%m-%d %H:%M:%S %Z')} - Generated by EmbedContainerView"
            ),
        )
        self.add_item(container)

    def _update_gallery(self) -> None:
        self.media_gallery.clear_items()
        updated_gallery = MediaGallery(index=self._cursor)
        for item in updated_gallery.attachments:
            self.media_gallery.add_item(media=item)
        self.media_gallery.attachments = updated_gallery.attachments
