site_name: Discord.py Masterclass
repo_url: https://github.com/FallenDeity/discord.py-masterclass
site_description: A hands-on guide to Discord.py
site_author: FallenDeity
copyright: Copyright FallenDeity ( 2023 - present )
site_url: https://fallendeity.github.io/discord.py-masterclass

theme:
  name: "material"
  language: en
  custom_dir: docs/overrides
  logo: assets/logo.png
  favicon: assets/logo.png

  font:
    text: Ubuntu

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.sections
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - toc.follow
    - toc.integrate
    - navigation.footer
    - search.suggest
    - search.share
  palette:
    - scheme: light
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Light Mode
    - scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-night
        name: Dark Mode

plugins:
  - glightbox:
      auto_caption: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_toc_entry: false
            docstring_style: numpy
            merge_init_into_class: true
            inherited_members: true
          inventories:
            - https://docs.python.org/3.9/objects.inv
            - http://discordpy.readthedocs.io/en/stable/objects.inv
  - search
  - social:
      cards_layout_options:
        background_color: "#3761A3"
        color: "#ffffff"



nav:
  - Getting Started: index.md
  - Guide:
    - Creating a Discord Bot: creating-a-bot.md
    - Cogs: cogs.md
    - Hybrid Commands: hybrid-commands.md
    - Slash Commands: slash-commands.md
    - Views: views.md
    - Custom Context: custom-context.md
    - Error Handling: error-handling.md
    - Converters: converters.md
    - Embeds: embeds.md
    - Checks: checks.md
    - Tasks: tasks.md
    - ANSI and Markdown: markdown-and-ansi.md
    - Audio Playback: audio-playback.md
  - Examples:
    - Pagination: pagination.md
    - Help Command: help-command.md

markdown_extensions:
  - tables
  - footnotes
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: ⚓︎
  - pymdownx.highlight:
      line_spans: __span
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true

extra:
  version: 0.1.0
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FallenDeity/discord.py-masterclass
    - icon: fontawesome/brands/discord
      link: https://discord.gg/dpy
  comments:
    enabled: true
    mode: giscus
  analytics:
    provider: google
    property: G-B1XSJ1S12C
